#!/bin/bash
less avx2_ledapkc1264_opt.yaml > avx2_ledapkc1364_opt.yaml
less avx2_ledapkc1264_opt.yaml > avx2_ledapkc1464_opt.yaml
less avx2_ledapkc1264_opt.yaml > avx2_ledapkc3364_opt.yaml
less avx2_ledapkc1264_opt.yaml > avx2_ledapkc5364_opt.yaml
less avx2_ledapkc1264_opt.yaml > avx2_ledapkc3464_opt.yaml
less avx2_ledapkc1264_opt.yaml > avx2_ledapkc3264_opt.yaml
less avx2_ledapkc1264_opt.yaml > avx2_ledapkc5464_opt.yaml
less avx2_ledapkc1264_opt.yaml > avx2_ledapkc5264_opt.yaml
        
less avx2_ledapkc1264_opt.yaml > avx2_ledapkc13sl_opt.yaml
less avx2_ledapkc1264_opt.yaml > avx2_ledapkc14sl_opt.yaml
less avx2_ledapkc1264_opt.yaml > avx2_ledapkc33sl_opt.yaml
less avx2_ledapkc1264_opt.yaml > avx2_ledapkc53sl_opt.yaml
less avx2_ledapkc1264_opt.yaml > avx2_ledapkc34sl_opt.yaml
less avx2_ledapkc1264_opt.yaml > avx2_ledapkc32sl_opt.yaml
less avx2_ledapkc1264_opt.yaml > avx2_ledapkc54sl_opt.yaml
less avx2_ledapkc1264_opt.yaml > avx2_ledapkc52sl_opt.yaml
less avx2_ledapkc1264_opt.yaml > avx2_ledapkc12sl_opt.yaml        
        
        

 

