name: Frontend Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
        cache-dependency-path: 'frontend/yarn.lock'
    - name: Install Validation Dependencies
      working-directory: tools/validation
      run: npm install
    - name: Create PQDB SQLite-File
      run: node tools/validation/validate.js frontend/public/pqdb.sqlite frontend/src/tables.svg
    - name: Install Frontend Dependencies and Build
      working-directory: frontend
      run: |
        yarn install
        yarn build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: frontend/build
        SINGLE_COMMIT: true
