name: Frontend Build and Deploy

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Create PQDB SQLite-File
      run: node tools/validation/validate.js pqdb-frontend/public/pqdb.sqlite
    - name: Install Dependencies and Build
      working-directory: pqdb-frontend
      run: |
        yarn install
        yarn build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: gh-pages
        FOLDER: pqdb-frontend/build
        SINGLE_COMMIT: true
